
version: '2'

services:
  pg-master:
    build: '.'
    image: 'geru/test-postgres-replication'
    container_name: test-postgres-master
    environment:
      POSTGRES_USER: 'geru'
      POSTGRES_PASSWORD: 'geru'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
     - 'postgres-master:/var/lib/postgresql/data'
    expose:
     - '5432'
    ports:
      - "5435:5432"

  pg-slave:
    build: '.'
    image: 'geru/test-postgres-replication'
    container_name: test-postgres-slave
    environment:
      POSTGRES_USER: 'geru'
      POSTGRES_PASSWORD: 'geru'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: 'pg-master'
    volumes:
     - 'postgres-slave:/var/lib/postgresql/data'
    expose:
     - '5432'
    ports:
     - '5436:5432'
    links:
     - pg-master

volumes:
  postgres-master:
  postgres-slave:
